#!/usr/bin/env bash
# This is a  script that audits DNS records for specified subdomains of a domain


if [$# == 2]; then
	domain = $1
	subdomain = $2
	SUB_DOMAINS = $subdomain
else
	domain = $1
	SUB_DOMAINS = ("www" "lb-01" "web-01" "web-02")
fi

for sub in ${SUB_DOMAINS[@]}; do
	record_type = "$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
	destination = $(dig +short "$sub.$domain" | awk '{print $1}')
	echo "The sudomain $sud is a $record_type and points to $destination"
done
